### ISSUE TITLE
Add instruction for using python3-xapian in debian

### ISSUE THREAD

**Issue by hsethi2709** [xapian/xapian-docsprint#27]
Currently it just says `python-xapian` for debian. It will be nice to add a line about using python3-xapian for debian. As it's confusing for new users.
```
$ sudo apt-get install python-xapian
```

**Comment by jaylett** [comment]
Given python2 is deprecated in the wild (although not in Debian yet, and not in Xapian yet), I wonder if we should push people towards 3 by showing only the 3 installation command.

**Comment by hsethi2709** [comment]
Well that makes sense. I'll remove the python2 instruction then.
