### ISSUE TITLE
The command failed when xapian installed for user only.

### ISSUE THREAD

**Issue by ywsswy** [xapian/xapian-docsprint#29]
I install xapian for user only.（./configure --prefix=/home/me/app/xapian）
so xapian-config is NOT in the system $PATH，and "make html LANGUAGE=c++" failed.

**Comment by ojwb** [comment]
You need to specify which xapian-config to use if it's not the first one on `PATH`:

```
make html LANGUAGE=c++ XAPIAN_CONFIG=/home/me/app/xapian/bin/xapian-config
```

Specifying `XAPIAN_CONFIG` is the standard way to specify a particular `xapian-config`, but doesn't seem to be explicitly documented here, which is unhelpful as this is where people will often start.  If you're looking to start contributing, a PR to address that would be great.

**Comment by ywsswy** [comment]
Oh, thanks. O(∩_∩)O
