### ISSUE TITLE
Broken URL on building_a_museum_catalogue

### ISSUE THREAD

**Issue by garethrees** [xapian/xapian-docsprint#8]
Broken URL: http://api.sciencemuseum.org.uk/documentation/collections/

https://github.com/xapian/xapian-docsprint/blob/master/practical_example/indexing/building_a_museum_catalogue.rst#building-a-museum-catalogue

**Comment by jaylett** [comment]
Great; Science Museum seems to have just withdrawn their APIs. Lovely. I believe we provide copies of the datasets for the time being.

**Comment by ojwb** [comment]
Thanks for reporting.  We do indeed have copies of the 100 entry subset we use, so I've fixed things up to make that clearer, but left the link in place with a note it wasn't working June 2015, in case this is a temporary issue.

I've also emailed their info email address to enquire.

@rboulton Did you know someone involved with this at the science museum?  If so, are they still there?

**Comment by ojwb** [comment]
The science museum replied - their api site was decommissioned, so I've updated to reflect that in edda75c3.
